wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [60, 60]
    rows: [3,7,40]
  refreshInterval: 60
  mods:
    check_backups:
      title: "Backups"
      cmd: "bash"
      args: ["/home/delaport/dotfiles/files/ts/check-backups.sh"]
      enabled: true
      position:
        top: 0
        left: 0
        width: 1
        height: 1
      type: cmdrunner
      refreshInterval: 6000
    todo_count:
      title: "Todo Count"
      cmd: "bash"
      args: ["/home/delaport/dotfiles/files/ts/todo_count.sh"]
      enabled: true
      position:
        top: 0
        left: 1
        width: 1
        height: 1
      type: cmdrunner
      refreshInterval: 6000
    in_progress:
      title: "In Progress"
      cmd: "bash"
      args: ["/home/delaport/dotfiles/files/ts/list-gh-in-progress.sh"]
      enabled: true
      position:
        top: 1
        left: 0
        width: 2
        height: 1
      type: cmdrunner
      refreshInterval: 60
    backlog:
      title: "GitHub Backlog"
      cmd: "bash"
      args: ["/home/delaport/dotfiles/files/ts/list-gh-board.sh"]
      enabled: true
      position:
        top: 2
        left: 0
        width: 2
        height: 1
      type: cmdrunner
      refreshInterval: 60
