codium --install-extension ban.spellright
codium --install-extension bierner.markdown-mermaid
codium --install-extension brunnerh.insert-unicodium
codium --install-extension ms-vscodium-remote.remote-containers
codium --install-extension ms-vscodium-remote.remote-ssh
codium --install-extension ms-vscodium-remote.remote-ssh-edit
codium --install-extension ms-vscodium-remote.remote-wsl
codium --install-extension ms-vscodium-remote.vscodium-remote-extensionpack
codium --install-extension ms-vscodium.remote-explorer
codium --install-extension ms-vscodium.remote-server
codium --install-extension pajoma.vscodium-journal
codium --install-extension rioj7.vscodium-json-validate
codium --install-extension tomasr8.close-all-but-this
codium --install-extension vscodiumvim.vim
codium --install-extension yzane.markdown-pdf
codium --install-extension yzhang.markdown-all-in-one
codium --install-extension ZainChen.json